kind: ConfigMap
metadata:
  name: flowcontrol
  namespace: aperture-system
  labels:
    aperture.tech/validate: "true"
apiVersion: v1
data:
  rate-limit-policy.yaml: |
    evaluation_interval: "0.5s"
    circuit:
      - constant:
          value: "250.0"
          out_ports:
            output:
              signal_name: "RATE_LIMIT"
      - rate_limiter:
          in_ports:
            limit:
              signal_name: "RATE_LIMIT"
          selector:
            namespace: "demoapp"
            service: "demo1-demo-app"
            control_point:
              traffic: "ingress"
          label_key: "request_header_user"
          limit_reset_interval: "1s"
