basePath: /aperture-controller
info:
  description: Aperture Controller
paths:
  /:
    post:
      operationId: ClassificationRule
      parameters:
      - in: body
        schema:
          $ref: '#/definitions/v1Classifier'
      tags:
      - classification-configuration
swagger: "2.0"
